definitions:
  schemas.TimeLog:
    type: object
info:
  contact: {}
paths:
  /Employee/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a employee
      tags:
      - employees
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
      summary: Get a list of employees
      tags:
      - employees
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update a employee
      tags:
      - employees
  /Employees/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Registration
        in: path
        name: register
        type: integer
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
      summary: Get a list of employees
      tags:
      - employees
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
      summary: Create employee
      tags:
      - employees
  /timeLogs:
    get:
      consumes:
      - application/json
      description: Retrieve all time logs for a specific employee
      parameters:
      - description: Employee ID
        in: query
        name: employee_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.TimeLog'
            type: array
        "400":
          description: Invalid employee ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get time logs
      tags:
      - timeLogs
    post:
      consumes:
      - application/json
      description: Create a new time log entry for an employee
      parameters:
      - description: Time Log Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.TimeLog'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schemas.TimeLog'
        "400":
          description: Invalid time log data
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a time log
      tags:
      - timeLogs
  /timeLogs/{id}:
    delete:
      description: Delete an existing time log entry for an employee
      parameters:
      - description: Time Log ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Time log deleted
          schema:
            type: string
        "404":
          description: Time log not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a time log
      tags:
      - timeLogs
    put:
      consumes:
      - application/json
      description: Update an existing time log entry for an employee
      parameters:
      - description: Time Log ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Time Log Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schemas.TimeLog'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.TimeLog'
        "400":
          description: Invalid time log data
          schema:
            type: string
        "404":
          description: Time log not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update a time log
      tags:
      - timeLogs
swagger: "2.0"
